### ISSUE TITLE
Unable to change expenses to "Paid" Status

### ISSUE THREAD

**Issue by SamirSaidani** [grap/odoo-addons-cae#12]
Config : 
ODOO 10
Odoo CAE module 10.0

Step to reproduce:
- Load the Expenses Module
- create a child fiscal society, and an accountant user (expenses manager)
- create an expense as a child fiscal society
- as an accountant user, approve & post the expense
- then click on "Register Payment" on the expense
- choose Bank or Cash
- the following message appears:

![image](https://user-images.githubusercontent.com/842380/84277396-bd8c6d00-ab33-11ea-869b-7214f6b09b77.png)

**Comment by legalsylvain** [comment]
Closing, as fiscal_company_hr_expense is not developped.
